workflows:
  android-lens-scanner:
    name: Lens Scanner Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.lensscanner.app"
      java: 17
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      
      - name: Get dependencies
        script: |
          ./gradlew dependencies
      
      - name: Build Android app
        script: |
          ./gradlew assembleDebug
    
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
      - app/build/outputs/**/mapping.txt
    
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
